npm install -g nodemon 
npm install -g http-server
npm install -g serverless
npm install -g @angular/cli 
npm install -g create-react-app
npm install -g pkg
npm install -g node-gyp
npm install -g npm-check-updates
npm install -g pm2
